spring.application.name=Backend

#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
#spring.datasource.username=root
#spring.datasource.password=1234

#New ? FreeSQLDatabase wala
spring.datasource.url=jdbc:mysql://sql8.freesqldatabase.com:3306/sql8828134
spring.datasource.username=sql8828134
spring.datasource.password=sEv4qaeNv4
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.web.resources.static-locations=file:uploads/

server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=false

cloudinary.cloud-name=drr2bt3iq
cloudinary.api-key=286883967492438
cloudinary.api-secret=0NW-F3kLQueVED1DPGnKBJ7GbOI